DROP TABLE IF EXISTS Restaurant CASCADE;
DROP TABLE IF EXISTS Food CASCADE;
DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Likes CASCADE;

CREATE TABLE Restaurant (
  RID integer PRIMARY KEY NOT NULL,
  Name text NOT NULL,
  Lat decimal NOT NULL,
  Long decimal NOT NULL
);

CREATE TABLE Food (
  FID integer PRIMARY KEY NOT NULL,
  RID integer NOT NULL,
  Name text NOT NULL,
  Price text NOT NULL,
  ImagePath text UNIQUE,
  FOREIGN KEY (RID) REFERENCES Restaurant(RID)
);

CREATE TABLE Users (
  UID serial PRIMARY KEY NOT NULL,
  LastFoodReset timestamp NOT NULL DEFAULT now()
);

CREATE TABLE Likes (
  UID integer NOT NULL,
  FID integer NOT NULL,
  Liked boolean NULL DEFAULT NULL,
  PRIMARY KEY(UID, FID),
  FOREIGN KEY (UID) REFERENCES Users(UID),
  FOREIGN KEY (FID) REFERENCES Food(FID)
);
